
[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[package]
name = "scant3r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
members = ["units","scanners","scripting"]

[[bin]]
name = "scant3r"
path = "cli/main.rs"

[dependencies]
isahc = "1.6.0"
url = "2.2.2"
scant3r_utils = {path ="./utils"}
scanners = {path = "./scanners"}
scripting = {path = "./scripting"}
serde_json = "1.0.79"
clap = "3.0.14"
home = "0.5.3"
tokio = { version = "0.2.18", features = ["full"] }
futures = "0.3.19"
indicatif = "0.16.2"
regex = "1.5.4"
hlua = "0.3"
