modules:
    xss:
        tags:
            - /home/knassar702/.scant3r/mod/xss/tags.txt
        jsfunc:
            - /home/knassar702/.scant3r/mod/xss/jsfunc.txt
        jsvalue:
            - /home/knassar702/.scant3r/mod/xss/jsvalue.txt
        attr:
            - /home/knassar702/.scant3r/mod/xss/attr.txt
